name: GitHub Actions Demo Java

on:
  push:
    branches:
      - main
      - jenk
  workflow_dispatch:

jobs:
  newjob:
    runs-on: ubuntu-latest
    
    steps:

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Show Java version
      run: "java -version"

    - name: Checkout mode
      uses: actions/checkout@v3
      with:
        ref: jenk
        
    - name: Show directory
      run: "pwd"

    - name: List files
      run: "ls -al"

    - name: Install dependencies
      run: "mvn compile"

    - name: Build application
      run: "mvn package -DskipTests"

    - name: Test Application
      run: "mvn test"
